-- Logging table to store debug messages
CREATE TABLE debug_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time     TIMESTAMP DEFAULT SYSTIMESTAMP,
    log_level    VARCHAR2(10),
    module_name  VARCHAR2(100),
    line_no      NUMBER,
    log_message  VARCHAR2(4000),
    session_id   VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

desc debug_log;

-- Package for debug utilities
CREATE OR REPLACE PACKAGE debug_utils AS
    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2 DEFAULT 'DEBUG'
    );

    PROCEDURE log_msg(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    );

    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    );

    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_err  IN VARCHAR2
    );
END debug_utils;
/

-- Package body implementation
CREATE OR REPLACE PACKAGE BODY debug_utils AS

    PROCEDURE write_log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO debug_log (
            log_level,
            module_name,
            line_no,
            log_message
        )
        VALUES (
            p_level,
            p_module_name,
            p_line,
            SUBSTR(p_message, 1, 4000)
        );

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END write_log;

    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;
    END enable_debug;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug_mode := FALSE;
    END disable_debug;

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2 DEFAULT 'DEBUG'
    ) IS
    BEGIN
        IF g_debug_mode THEN
            write_log(p_module_name, p_line, p_message, p_level);
        END IF;
    END log;

    PROCEDURE log_msg(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            write_log(p_module_name, p_line, p_message, 'INFO');
        END IF;
    END log_msg;

    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    ) IS
    BEGIN
        IF g_debug_mode THEN
            write_log(
                p_module_name,
                p_line,
                p_name || ' = ' || p_value,
                'DEBUG'
            );
        END IF;
    END log_variable;

    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_err  IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_proc,
            NULL,
            p_err,
            'ERROR'
        );
    END log_error;

END debug_utils;
/

SHOW ERRORS;