CREATE USER etl IDENTIFIED BY etl
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO etl;
GRANT CREATE TABLE TO etl;
GRANT CREATE VIEW TO etl;
GRANT CREATE SEQUENCE TO etl;
GRANT CREATE PROCEDURE TO etl;
GRANT CREATE TRIGGER TO etl;
GRANT CREATE SYNONYM TO etl;

-- =====================================================
-- 1. DEPARTMENT
-- Stores the departments in the company
-- =====================================================
CREATE TABLE department (
    department_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name  VARCHAR2(100) NOT NULL,
    cost_center      VARCHAR2(20),
    created_at       DATE DEFAULT SYSDATE,

    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uq_department_name UNIQUE (department_name),
    CONSTRAINT uq_department_cost_center UNIQUE (cost_center)
);

-- =====================================================
-- 2. EMPLOYEE
-- Stores employees who submit timesheets
-- profile_json is a semi-structured JSON field
-- =====================================================
CREATE TABLE employee (
    employee_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id       NUMBER NOT NULL,
    employee_code       VARCHAR2(20) NOT NULL,
    first_name          VARCHAR2(50) NOT NULL,
    last_name           VARCHAR2(50) NOT NULL,
    email               VARCHAR2(100) NOT NULL,
    hire_date           DATE DEFAULT SYSDATE,
    employment_status   VARCHAR2(20) DEFAULT 'ACTIVE',
    profile_json        CLOB,

    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department(department_id),
    CONSTRAINT uq_employee_code UNIQUE (employee_code),
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT ck_employee_status
        CHECK (employment_status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
    CONSTRAINT ck_employee_profile_json
        CHECK (profile_json IS JSON)
);

-- =====================================================
-- 3. PROJECT
-- Stores projects where employees can log time
-- =====================================================
CREATE TABLE project (
    project_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    project_code     VARCHAR2(20) NOT NULL,
    project_name     VARCHAR2(100) NOT NULL,
    start_date       DATE,
    end_date         DATE,
    project_status   VARCHAR2(20) DEFAULT 'PLANNED',
    budget_hours     NUMBER(8,2) DEFAULT 0,

    CONSTRAINT pk_project PRIMARY KEY (project_id),
    CONSTRAINT uq_project_code UNIQUE (project_code),
    CONSTRAINT ck_project_status
        CHECK (project_status IN ('PLANNED', 'ACTIVE', 'CLOSED')),
    CONSTRAINT ck_project_budget_hours
        CHECK (budget_hours >= 0),
    CONSTRAINT ck_project_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

-- =====================================================
-- 4. TIMESHEET
-- Stores one weekly timesheet per employee
-- =====================================================
CREATE TABLE timesheet (
    timesheet_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id        NUMBER NOT NULL,
    week_start_date    DATE NOT NULL,
    week_end_date      DATE NOT NULL,
    status             VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    submitted_at       DATE,

    CONSTRAINT pk_timesheet PRIMARY KEY (timesheet_id),
    CONSTRAINT fk_timesheet_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT uq_timesheet_employee_week UNIQUE (employee_id, week_start_date),
    CONSTRAINT ck_timesheet_status
        CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_timesheet_week_dates
        CHECK (week_end_date >= week_start_date)
);

-- =====================================================
-- 5. TIMESHEET_ENTRY
-- Stores detailed daily work records inside a timesheet
-- =====================================================
CREATE TABLE timesheet_entry (
    entry_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    timesheet_id        NUMBER NOT NULL,
    project_id          NUMBER NOT NULL,
    work_date           DATE NOT NULL,
    hours_worked        NUMBER(4,2) NOT NULL,
    task_type           VARCHAR2(20) NOT NULL,
    work_description    VARCHAR2(255) NOT NULL,
    billable_flag       CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_timesheet_entry PRIMARY KEY (entry_id),
    CONSTRAINT fk_entry_timesheet
        FOREIGN KEY (timesheet_id) REFERENCES timesheet(timesheet_id),
    CONSTRAINT fk_entry_project
        FOREIGN KEY (project_id) REFERENCES project(project_id),
    CONSTRAINT ck_entry_hours
        CHECK (hours_worked > 0 AND hours_worked <= 24),
    CONSTRAINT ck_entry_task_type
        CHECK (task_type IN ('DEV', 'TEST', 'MEETING', 'SUPPORT', 'DOC')),
    CONSTRAINT ck_entry_billable
        CHECK (billable_flag IN ('Y', 'N'))
);

-- Additional indexes besides PK and FK indexes
CREATE INDEX idx_employee_last_name
    ON employee(last_name);

CREATE INDEX idx_project_name
    ON project(project_name);

CREATE INDEX idx_timesheet_entry_work_date
    ON timesheet_entry(work_date);


-- Staging tables for raw data ingestion
CREATE TABLE stg_timesheet_activity (
    entry_id            NUMBER,
    employee_code       VARCHAR2(20),
    project_code        VARCHAR2(20),
    work_date           DATE,
    hours_worked        NUMBER(4,2),
    task_type           VARCHAR2(20),
    work_description    VARCHAR2(255),
    billable_flag       CHAR(1)
);

CREATE TABLE stg_event_calendar (
    event_id            NUMBER,
    employee_code       VARCHAR2(20),
    event_date          DATE,
    event_name          VARCHAR2(100),
    event_type          VARCHAR2(30),
    duration_hours      NUMBER(4,2),
    location            VARCHAR2(100)
);

CREATE TABLE stg_absence_log (
    absence_id          NUMBER,
    employee_code       VARCHAR2(20),
    absence_date        DATE,
    absence_type        VARCHAR2(30),
    absence_hours       NUMBER(4,2),
    approval_status     VARCHAR2(20)
);



-- Dimension tables for data warehouse
CREATE TABLE dim_department (
    department_key     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id_src  NUMBER,
    department_name    VARCHAR2(100),
    cost_center        VARCHAR2(20)
);

CREATE TABLE dim_employee (
    employee_key         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id_src      NUMBER,
    employee_code        VARCHAR2(20),
    first_name           VARCHAR2(50),
    last_name            VARCHAR2(50),
    email                VARCHAR2(100),
    hire_date            DATE,
    employment_status    VARCHAR2(20),
    department_key       NUMBER,
    CONSTRAINT fk_dim_employee_department
        FOREIGN KEY (department_key) REFERENCES dim_department(department_key)
);

CREATE TABLE dim_project (
    project_key        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id_src     NUMBER,
    project_code       VARCHAR2(20),
    project_name       VARCHAR2(100),
    start_date         DATE,
    end_date           DATE,
    project_status     VARCHAR2(20),
    budget_hours       NUMBER(8,2)
);

CREATE TABLE dim_date (
    date_key           NUMBER PRIMARY KEY,
    full_date          DATE NOT NULL,
    day_number         NUMBER,
    month_number       NUMBER,
    month_name         VARCHAR2(20),
    quarter_number     NUMBER,
    year_number        NUMBER,
    weekday_name       VARCHAR2(20),
    is_weekend         CHAR(1)
);

CREATE TABLE dim_activity_type (
    activity_type_key   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system       VARCHAR2(20),
    activity_category   VARCHAR2(30),
    activity_subtype    VARCHAR2(30),
    billable_flag       CHAR(1)
);



-- Fact table for timesheet entries
CREATE TABLE fact_employee_activity (
    activity_fact_key      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key               NUMBER NOT NULL,
    employee_key           NUMBER NOT NULL,
    department_key         NUMBER NOT NULL,
    project_key            NUMBER,
    activity_type_key      NUMBER NOT NULL,
    source_record_id       NUMBER,
    source_system          VARCHAR2(20) NOT NULL,
    activity_description   VARCHAR2(255),
    hours_amount           NUMBER(6,2) DEFAULT 0,
    activity_count         NUMBER DEFAULT 1,

    CONSTRAINT fk_fact_date
        FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
    CONSTRAINT fk_fact_employee
        FOREIGN KEY (employee_key) REFERENCES dim_employee(employee_key),
    CONSTRAINT fk_fact_department
        FOREIGN KEY (department_key) REFERENCES dim_department(department_key),
    CONSTRAINT fk_fact_project
        FOREIGN KEY (project_key) REFERENCES dim_project(project_key),
    CONSTRAINT fk_fact_activity_type
        FOREIGN KEY (activity_type_key) REFERENCES dim_activity_type(activity_type_key)
);